{
 "title": "prometheus-apt-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "upgradable packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(dns_name) (pkg_upgradable) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "broken packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(dns_name) (pkg_broken) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hosts need reboot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "targets": [
    { "expr": "pkg_reboot_required > 0", "legendFormat": "{{dns_name}}" }
   ]
  }
 ]
}